import { VSBuffer } from '../../vs/base/common/buffer.js';
import { URI } from '../../vs/base/common/uri.js';
import { IFileService } from '../../vs/platform/files/common/files.js';
import { IEditorService } from '../../vs/workbench/services/editor/common/editorService.js';

export class PlanWorkspaceService {
	constructor(
		private readonly fileService: IFileService,
		private readonly editorService: IEditorService
	) {}

	async createInitialPlan(workspaceRootFsPath: string): Promise<URI> {
		const workspaceRoot = URI.file(workspaceRootFsPath);

		const plansFolder = URI.joinPath(workspaceRoot, '.onyx', 'plans');
		const fileUri = URI.joinPath(plansFolder, 'ONYX_PLAN.md');

		const initialContent = `# ONYX Plan Workspace

## Objective
Define and execute an intelligence systems design, execution, and control plan.

## Tasks
- [ ] Define architecture
- [ ] Define governed execution flow
- [ ] Implement services
- [ ] Integrate UI
- [ ] Add approvals and reporting

## Notes
This plan workspace was generated by ONYX.
`;

		await this.fileService.createFolder(plansFolder);

		await this.fileService.writeFile(
			fileUri,
			VSBuffer.fromString(initialContent)
		);

		await this.editorService.openEditor({
			resource: fileUri
		});

		return fileUri;
	}
}